version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    working_dir: /app/apps/api
    env_file:
      - ./apps/api/.env
    ports:
      - "3000:3000"  # adjust to your API port
    depends_on:
      - minio
    volumes:
      - .:/app
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    working_dir: /app/apps/web
    ports:
      - "5173:5173"  # React app port
    volumes:
      - .:/app
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: youraccesskey
      MINIO_ROOT_PASSWORD: yoursecretkey
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:
